# Generated by Django 2.2.2 on 2019-08-10 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_no', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('top_rated', models.CharField(max_length=250)),
                ('ques', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mock_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.topics')),
            ],
        ),
    ]
