# Generated by Django 2.2.2 on 2019-08-13 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20190810_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Topics'),
        ),
    ]
