# Generated by Django 2.2.2 on 2019-09-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20190813_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktest',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Topics'),
        ),
    ]
