# Generated by Django 2.2.2 on 2019-09-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20190904_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktest',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Topics'),
        ),
    ]
